### ISSUE TITLE
How to input text to generate images other than the RSICD dataset? 

### ISSUE THREAD

**Issue by jaycecd** [YonghaoXu/Txt2Img-MHN#7]
For example, if I want to generate an airport, where should I input it？

At present, it seems that only images corresponding to the RSICD dataset can be generated.

Looking forward to your reply, thank you！

**Comment by jaycecd** [comment]
The root of the question is: does the file `'./tools/rsicd_vocab_5000.txt'` contain the bpe encoding for all words rather than just encoding for RSICD? 

For example, if there is no `dog (word)` in the RSICD dataset, does `./tools/rsicd_vocab_5000.txt` encode the word of dog?

If `./tools/rsicd_vocab_5000.txt` doesn't encode all the words, what should I do if I want to generate images using prompts other than RSICD?

**Comment by YonghaoXu** [comment]
If you want to generate images based on customed text descriptions, you can prepare a `txt` file containing the descriptions and read this file with the `gen_im.py` (with some minor adaptation). 

Note that the provided tokenizer `rsicd_vocab_5000.txt` is trained using the captions in the RSICD dataset only. Thus, it is not suitable to use it for natural image generation. You can follow the instructions in `data_preparation.py` to train a new tokenizer if necessary.

**Comment by jaycecd** [comment]
Thanks for the reply, unfortunately, I prepared `caption_all_txt` and `test_list` based on `data_preparation.py`, and successfully used bpe to train my own tokenizer; in addition, I have modified `bpe_path` in `class YttmTokenizer` to my own tokenizer path, and then use `gen.im.py` generates images and reports an error:
```python
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips\vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Loaded VQGAN from D:\Code\Python\Git\Txt2Img-MHN\model\Txt2Img-MHN_VQGAN\last.ckpt and D:\Code\Python\Git\Txt2Img-MHN\model\Txt2Img-MHN_VQGAN\2022-07-19T16-49-53-project.yaml
Traceback (most recent call last):
  File "gen_im.py", line 67, in <module>
    main(parser.parse_args())
  File "gen_im.py", line 34, in main
    model.load_state_dict(new_params)
  File "C:\Users\Jayce\Anaconda3\envs\Txt2Img-MHN\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Txt2ImgMHN:
        size mismatch for text_emb.weight: copying a param with shape torch.Size([5040, 512]) from checkpoint, the shape in current model is torch.Size([477, 512]).
        size mismatch for content.0.weight: copying a param with shape torch.Size([6064, 1000]) from checkpoint, the shape in current model is torch.Size([1501, 1000]).
        size mismatch for content.1.weight: copying a param with shape torch.Size([6064]) from checkpoint, the shape in current model is torch.Size([1501]).
        size mismatch for content.1.bias: copying a param with shape torch.Size([6064]) from checkpoint, the shape in current model is torch.Size([1501]).
```

how to solve this problem?

**Comment by YonghaoXu** [comment]
Hi, it seems that you are trying to load the provided model with your own tokenizer. This would lead to a mismatch as the vocabulary size has been changed in the new tokenizer. Besides, even if the vocabulary size remains the same in the new tokenizer, you still need to retrain the whole text-to-image generation model as the obtained text tokens have been changed.

**Comment by jaycecd** [comment]
Sadly, this means that I need to retrain the entire generative model whenever I generate remote sensing images using prompts other than RSICD.

On top of that, even if the words in the prompt appear in RSICD, just not in the same order as RSICD, the whole model needs to be retrained.

This is too costly to use.
